SELECT s.Student_ID, s.Name, c.Course_Name
FROM Student s
JOIN Enrollment e ON s.Student_ID = e.Student_ID
JOIN Course c ON e.Course_ID = c.Course_ID;


SELECT s.STUDENT_ID, s.Name, c.COURSE_NAME
FROM STUDENT s
LEFT JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID
LEFT JOIN COURSE c ON c.COURSE_ID = e.COURSE_ID;


SELECT s.NAME AS STUDENT_NAME, c.COURSE_NAME
FROM STUDENT s
RIGHT JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID
RIGHT JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID;

SELECT s.Name AS Student_Name, c.Course_Name
FROM Student s
FULL OUTER JOIN Enrollment e ON s.Student_ID = e.Student_ID
FULL OUTER JOIN Course c ON e.Course_ID = c.Course_ID;


SELECT s.NAME AS STUDENT_NAME, c.COURSE_NAME
FROM STUDENT s
CROSS JOIN COURSE c;


SELECT e1.NAME AS STUDENT1, e2.NAME AS STUDENT2
FROM STUDENT e1, STUDENT e2
WHERE e1.STUDENT_ID<>e2.STUDENT_ID;


SELECT NAME, ADDRESS
FROM STUDENT
WHERE(
    SELECT STUDENT_ID FROM ENROLLMENT WHERE COURSE_ID = 102
);


SELECT NAME
FROM STUDENT
WHERE STUDENT_ID IN (
    SELECT STUDENT_ID FROM ENROLLMENT WHERE COURSE_ID IN (101,102)
);


SELECT NAME
FROM STUDENT s
WHERE EXISTS(
    SELECT * FROM ENROLLMENT e WHERE e.STUDENT_ID = s.STUDENT_ID
);


CREATE OR REPLACE VIEW StudentCourseView AS 
SELECT 
    s.STUDENT_ID,
    s.NAME AS STUDENT_NAME,
    c.COURSE_NAME,
    i.NAME AS INSTRUCTOR_NAME
FROM STUDENT s
JOIN ENROLLMENT e ON s.STUDENT_ID = e.STUDENT_ID
JOIN COURSE c ON e.COURSE_ID = c.COURSE_ID
JOIN INSTRUCTOR i ON c.INSTRUCTOR_ID = i.INSTRUCTOR_ID

SELECT * FROM StudentCourseView;
    