CREATE TABLE Stud_Marks(
    name VARCHAR2(30),
    total_marks NUMBER
);

CREATE TABLE Result(
    roll NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(30),
    class VARCHAR2(30)
);


INSERT INTO Stud_Marks VALUES('Booker', 1450);
INSERT INTO Stud_Marks VALUES('Sarge', 950);
INSERT INTO Stud_Marks VALUES('Ritul', 880);
INSERT INTO Stud_Marks VALUES('Sarang', 790);

SELECT * FROM Stud_Marks;

CREATE OR REPLACE PROCEDURE proc IS 
    CURSOR stud_cur IS
        SELECT name, total_marks FROM Stud_Marks;
    v_name Stud_Marks.name%TYPE;
    v_marks Stud_Marks.total_marks%TYPE;
    v_class VARCHAR2(30);
BEGIN
    OPEN stud_cur;
    LOOP
        FETCH stud_cur INTO v_name, v_marks;
        EXIT WHEN stud_cur%NOTFOUND;

        IF v_marks BETWEEN 990 AND 1500 THEN
            v_class := 'DISTINCTION';
        ELSIF v_marks BETWEEN 900 AND 989 THEN
            v_class := 'First class';
        ELSIF v_marks BETWEEN 825 AND 899 THEN
            v_class := 'Higher Second Class';
        ELSE 
            v_class := 'Fail';
        END IF;

        INSERT INTO Result (name, class)
        VALUES (v_name, v_class);
    END LOOP;
    CLOSE stud_cur;
END;


BEGIN
    PROC;
END;


SELECT * FROM Result;