CREATE TABLE Library(
    BOOK_ID NUMBER PRIMARY KEY,
    BOOK_Name VARCHAR2(30),
    Author VARCHAR2(30),
    Price NUMBER
);

CREATE TABLE Library_Audit(
    Audit_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BOOK_ID NUMBER,
    BOOK_Name VARCHAR2(30),
    Author VARCHAR2(30),
    Price NUMBER,
    Action_Type VARCHAR2(10),
    Action_Date DATE
);


INSERT INTO Library VALUES(1, 'abcd', 'efg', 100);
INSERT INTO Library VALUES(2, 'hijk', 'lmn', 300);
INSERT INTO Library VALUES(3, 'opqr', 'stu', 350);
COMMIT;

CREATE OR REPLACE TRIGGER trr_audit
AFTER UPDATE OR DELETE
ON Library
FOR EACH ROW
BEGIN
    IF UPDATING THEN
        INSERT INTO Library_audit(BOOK_ID, BOOK_Name, Author, Price, Action_Type, Action_Date)
        VALUES(:OLD.BOOK_ID, :OLD.BOOK_Name, :OLD.Author, :OLD.Price, 'UPDATE', SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO Library_audit(BOOK_ID, BOOK_Name, Author, Price, Action_Type, Action_Date)
        VALUES(:OLD.BOOK_ID, :OLD.BOOK_Name, :OLD.Author, :OLD.Price, 'DELETE', SYSDATE);
    END IF;
END;


UPDATE Library SET Price = 80 WHERE BOOK_ID = 1;

SELECT * FROM LIBRARY_AUDIT;